version: "3.8"
services:
  app2:
    environment:
      - PUID=1001
      - PGID=1002
    networks:
      - web-dev
    ports:
      # Listen on port 80, default for HTTP
      - target: 80
        published: 8082
        mode: host
    volumes:
      - .:/var/www/html/:cached
    depends_on:
      - "mariadb"

networks:
  web-dev:
    name: shared-network
