version: "3.8"
services:
  mariadb:
    image: mariadb:10.7
    networks:
      - web-dev
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MARIADB_DATABASE: "laravel"
      MARIADB_USER: "example-app-user"
      MARIADB_PASSWORD: "example-app-password"
    volumes:
      # Add volume for all database files
      - ./_volumes/mysql/database_data/:/var/lib/mysql
      # Add volume for custom configurations
      - ./_volumes/mysql/conf.d/:/etc/mysql/conf.d
      - ./_volumes/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - target: 3306
        published: 33061
        mode: host

networks:
  web-dev:
    name: shared-network
